- type: job
  id: Detective
  name: job-name-detective
  description: job-description-detective
  playTimeTracker: JobDetective
  requirements:
    # LP edit start
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 4h
    - !type:SpeciesRequirement
      inverted: true
      species:
      - Diona
    # LP edit end
    - !type:TraitsRequirement #Corvax-TraitsRequirement
      inverted: true
      traits:
      - Muted
  startingGear: DetectiveGear
  icon: "JobIconDetective"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Detective
  - Cryogenics
  - External
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: DetectiveGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: DetectivePDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltHolsterFilled
  storage:
    back:
    - Flash
    - ForensicPad
    - ForensicScanner

- type: chameleonOutfit
  id: DetectiveChameleonOutfit
  job: Detective
  hasMindShield: true
  equipment:
    head: ClothingHeadHatFedoraBrown
    mask: ClothingMaskGasSecurity
    neck: ClothingNeckTieDet
    gloves: ClothingHandsGlovesForensic
