# За баланс хз, вроде достаточно дорогие
- type: latheRecipe 
  id: LPBorgModuleSecurityWeapon
  result: LPBorgModuleSecurityWeapon
  materials:
    Steel: 2000
    Glass: 800
    Plastic: 500

- type: latheRecipe 
  id: LPBorgModuleSecurityLaserCarbine
  result: LPBorgModuleSecurityLaserCarbine
  materials:
    Steel: 3000
    Glass: 1000
    Plastic: 500