name: "Labels: PR"

on:
- pull_request_target

jobs:
  labeler:
    if: github.actor != 'IanComradeBot' && github.actor != 'Lost-Paradise-Bot'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
