name: "Labels: Changes"

on:
  pull_request_review:
    types: [submitted]

jobs:
  update_label:
    if: github.event.review.state == 'changes_requested'
    runs-on: ubuntu-latest
    steps:
    - uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: "Статус: Ожидание изменений"
    - uses: actions-ecosystem/action-remove-labels@v1
      with:
        labels: "Статус: Ожидание проверки"
