name: RSI Validator Secrets

on:
  push:
    branches: [ master, staging, stable ]
  merge_group:
  pull_request:
    paths:
    - '**.rsi/**'

jobs:
  validate_rsis:
    name: Validate RSIs
    if: ${{ vars.SECRETSLINK != '' && github.actor != 'PJBot' && github.event.pull_request.draft == false && github.actor != 'Lost-Paradise-Bot' }}
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3.6.0
    - name: Download parts
      run: |
        git clone ${{ secrets.SECRETS }}
        mv NewSecrets/PResources/PPrototypes Resources/Prototypes/
        mv NewSecrets/PResources/PTextures Resources/Textures/
        mv NewSecrets/PShared Content.Shared/PShared
        mv NewSecrets/PServer Content.Server/PServer
        mv NewSecrets/PClient Content.Client/PClient
    - name: Setup Submodule
      run: git submodule update --init
    - name: Pull engine updates
      uses: space-wizards/submodule-dependency@v0.1.5
    - name: Install Python dependencies
      run: |
        pip3 install --ignore-installed --user pillow jsonschema
    - name: Validate RSIs
      run: |
        python3 RobustToolbox/Schemas/validate_rsis.py Resources/
